import { randomBytes } from "node:crypto";
import { asc, eq } from "drizzle-orm";
import { decryptCredentials } from "@/core/security/credentials";
import { createProvider } from "@/core/providers/provider-factory";
import { UploadOrchestrator } from "./upload-orchestrator";
import { LoadedImage } from "./source-loader";
import { getDb } from "@/db/client";
import { fallbackChainItems, imageReplicas, images, providerConnections, shortLinks } from "@/db/schema";
export async function createImage(accountId: string, input: LoadedImage) { const db = getDb(); const [created] = await db.insert(images).values({ accountId, originalUrl: input.originalUrl, contentType: input.contentType, byteSize: input.bytes.byteLength, sha256: input.sha256, status: "processing" }).returning(); const chain = await db.select().from(fallbackChainItems).where(eq(fallbackChainItems.accountId, accountId)).orderBy(asc(fallbackChainItems.position)); const connections = await db.select().from(providerConnections).where(eq(providerConnections.accountId, accountId)); const selected = chain.map((item) => connections.find((connection) => connection.provider === item.provider && connection.enabled)).filter((item): item is NonNullable<typeof item> => Boolean(item)); if (!selected.length) { await db.update(images).set({ status: "failed" }).where(eq(images.id, created.id)); throw new Error("Connect and enable at least one provider in your fallback chain."); } const extension = input.contentType.split("/")[1]?.replace(/[^a-z0-9]/gi, "") || "bin"; const result = await new UploadOrchestrator().replicate({ bytes: input.bytes, contentType: input.contentType, objectKey: `${accountId}/${input.sha256}.${extension}` }, selected.map((connection) => createProvider(connection.provider, decryptCredentials(connection.encryptedCredentials)))); const ready = result.replicas.filter((replica) => replica.status === "ready"); await db.insert(imageReplicas).values(result.replicas.map((replica) => ({ imageId: created.id, provider: replica.provider, status: replica.status, externalId: replica.result?.externalId, providerUrl: replica.result?.publicUrl, failureReason: replica.error }))); if (!ready.length) { await db.update(images).set({ status: "failed" }).where(eq(images.id, created.id)); throw new Error("Every provider upload failed."); } const code = randomBytes(7).toString("base64url"); await db.update(images).set({ status: result.status }).where(eq(images.id, created.id)); const [link] = await db.insert(shortLinks).values({ imageId: created.id, code }).returning(); return { image: created, status: result.status, shortCode: link.code, replicas: ready }; }
