import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import { providerTypes } from "@/core/providers/types";

export const providerType = pgEnum("provider_type", providerTypes);
export const imageStatus = pgEnum("image_status", ["processing", "ready", "degraded", "failed"]);
export const imageEventType = pgEnum("image_event_type", ["uploaded", "degraded", "repair_started", "replica_repaired", "repair_failed"]);
export const replicaStatus = pgEnum("replica_status", ["pending", "ready", "failed"]);

export const accounts = pgTable("accounts", { id: uuid("id").defaultRandom().primaryKey(), clerkUserId: varchar("clerk_user_id", { length: 128 }).notNull().unique(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const providerConnections = pgTable("provider_connections", { id: uuid("id").defaultRandom().primaryKey(), accountId: uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }), provider: providerType("provider").notNull(), encryptedCredentials: text("encrypted_credentials").notNull(), keyVersion: integer("key_version").notNull().default(1), enabled: boolean("enabled").notNull().default(true), validatedAt: timestamp("validated_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("provider_connection_account_provider").on(t.accountId, t.provider)]);
export const compressionSettings = pgTable("compression_settings", { id: uuid("id").defaultRandom().primaryKey(), accountId: uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }).unique(), enabled: boolean("enabled").notNull().default(false), config: jsonb("config").$type<{ defaultFormat: "webp" | "avif"; defaultQuality: number; maxWidth?: number; maxHeight?: number; rules: Array<{ mimeTypes?: string[]; extensions?: string[]; action: "skip" | "compress"; format?: "webp" | "avif"; quality?: number }> }>().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const fallbackChainItems = pgTable("fallback_chain_items", { id: uuid("id").defaultRandom().primaryKey(), accountId: uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }), provider: providerType("provider").notNull(), position: integer("position").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("fallback_chain_account_provider").on(t.accountId, t.provider), uniqueIndex("fallback_chain_account_position").on(t.accountId, t.position)]);
export const images = pgTable("images", { id: uuid("id").defaultRandom().primaryKey(), accountId: uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }), originalUrl: text("original_url"), contentType: varchar("content_type", { length: 128 }).notNull(), byteSize: integer("byte_size").notNull(), sha256: varchar("sha256", { length: 64 }).notNull(), status: imageStatus("status").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("images_account_created").on(t.accountId, t.createdAt)]);
export const imageReplicas = pgTable("image_replicas", { id: uuid("id").defaultRandom().primaryKey(), imageId: uuid("image_id").notNull().references(() => images.id, { onDelete: "cascade" }), provider: providerType("provider").notNull(), providerUrl: text("provider_url"), externalId: text("external_id"), status: replicaStatus("status").notNull(), failureReason: text("failure_reason"), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("replica_image_provider").on(t.imageId, t.provider)]);
export const shortLinks = pgTable("short_links", { id: uuid("id").defaultRandom().primaryKey(), imageId: uuid("image_id").notNull().references(() => images.id, { onDelete: "cascade" }), code: varchar("code", { length: 24 }).notNull().unique(), active: boolean("active").notNull().default(true), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const imageEvents = pgTable("image_events", { id: uuid("id").defaultRandom().primaryKey(), imageId: uuid("image_id").notNull().references(() => images.id, { onDelete: "cascade" }), type: imageEventType("type").notNull(), provider: providerType("provider"), message: text("message"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("image_events_image_created").on(t.imageId, t.createdAt)]);
export const apiKeys = pgTable("api_keys", { id: uuid("id").defaultRandom().primaryKey(), accountId: uuid("account_id").notNull().references(() => accounts.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), prefix: varchar("prefix", { length: 24 }).notNull(), secretHash: varchar("secret_hash", { length: 128 }).notNull(), scopes: jsonb("scopes").$type<string[]>().notNull().default([]), expiresAt: timestamp("expires_at", { withTimezone: true }), revokedAt: timestamp("revoked_at", { withTimezone: true }), lastUsedAt: timestamp("last_used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("api_key_prefix_unique").on(t.prefix)]);
