"use client";
import { DndProvider, useDrag, useDrop } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";
import { useEffect, useRef, useState } from "react";
type Provider = "link" | "cloudinary" | "imagekit" | "s3" | "firebase";
const TYPE = "fallback-provider";
function Row({ provider, index, move }: { provider: Provider; index: number; move: (from: number, to: number) => void }) { const ref = useRef<HTMLDivElement>(null); const [, drop] = useDrop<{ index: number }>({ accept: TYPE, hover(item) { if (item.index !== index) { move(item.index, index); item.index = index; } } }); const [, drag] = useDrag(() => ({ type: TYPE, item: { index } }), [index]); drag(drop(ref)); return <div ref={ref} className="flex cursor-grab items-center justify-between rounded-xl border border-slate-700 bg-slate-900 px-4 py-4 active:cursor-grabbing"><span className="text-slate-500">⠿</span><span className="ml-3 flex-1 capitalize">{provider}</span><span className="text-xs text-cyan-300">priority {index + 1}</span></div>; }
function Editor() { const [chain, setChain] = useState<Provider[]>([]); const [connected, setConnected] = useState<Provider[]>([]); const [message, setMessage] = useState(""); useEffect(() => { void Promise.all([fetch("/api/v1/fallback-chain").then((r) => r.json()), fetch("/api/v1/providers").then((r) => r.json())]).then(([fallback, providers]) => { setChain(fallback.data?.map((item: { provider: Provider }) => item.provider) ?? []); setConnected(["link", ...(providers.data?.filter((item: { enabled: boolean }) => item.enabled).map((item: { provider: Provider }) => item.provider) ?? [])]); }); }, []); const move = (from: number, to: number) => setChain((items) => { const next = [...items]; const selected = next[from]; if (selected === "link" || (next.includes("link") && to === 0)) return items; next.splice(to, 0, next.splice(from, 1)[0]); return next; }); const missing = connected.filter((provider) => !chain.includes(provider)); async function save() { const response = await fetch("/api/v1/fallback-chain", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ providers: chain }) }); setMessage(response.ok ? "Fallback order saved." : (await response.json()).error); } return <main className="min-h-screen bg-slate-950 px-6 py-12 text-slate-100"><div className="mx-auto max-w-2xl"><p className="text-sm font-medium text-cyan-300">SETTINGS / FALLBACK CHAIN</p><h1 className="mt-2 text-4xl font-semibold">Choose the delivery order.</h1><p className="mt-3 text-slate-400">LinkProvider is optional, but when enabled it stays first and preserves source URLs. Existing shortlinks use this order immediately.</p><div className="mt-8 space-y-3">{chain.map((provider, index) => <Row key={provider} provider={provider} index={index} move={move} />)}</div>{missing.length > 0 && <button className="mt-5 rounded-lg border border-slate-700 px-4 py-2 text-sm" onClick={() => setChain(chain.includes("link") ? [...chain, ...missing.filter((p) => p !== "link")] : [...missing, ...chain])}>Add connected providers</button>}<div className="mt-8"><button className="rounded-lg bg-cyan-300 px-5 py-3 font-medium text-slate-950" onClick={save}>Save order</button><p className="mt-3 text-sm text-slate-400">{message}</p></div></div></main>; }
export default function FallbackChainPage() { return <DndProvider backend={HTML5Backend}><Editor /></DndProvider>; }
