import { auth } from "@clerk/nextjs/server";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { ensureAccount } from "@/core/accounts/account-service";
import { encryptCredentials } from "@/core/security/credentials";
import { createProvider } from "@/core/providers/provider-factory";
import { providerTypes } from "@/core/providers/types";
import { getDb } from "@/db/client";
import { providerConnections } from "@/db/schema";
const schema = z.object({ provider: z.enum(providerTypes), credentials: z.unknown(), enabled: z.boolean().default(true) });
export async function GET() { const { userId } = await auth(); if (!userId) return Response.json({ error: "Unauthorized" }, { status: 401 }); const account = await ensureAccount(userId); const data = await getDb().select({ id: providerConnections.id, provider: providerConnections.provider, enabled: providerConnections.enabled, validatedAt: providerConnections.validatedAt }).from(providerConnections).where(eq(providerConnections.accountId, account.id)); return Response.json({ data }); }
export async function PUT(request: Request) { const { userId } = await auth(); if (!userId) return Response.json({ error: "Unauthorized" }, { status: 401 }); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: "Invalid payload", details: parsed.error.flatten() }, { status: 422 }); const account = await ensureAccount(userId); try { const provider = createProvider(parsed.data.provider, parsed.data.credentials); await provider.validateCredentials(parsed.data.credentials); await getDb().insert(providerConnections).values({ accountId: account.id, provider: parsed.data.provider, encryptedCredentials: encryptCredentials(parsed.data.credentials), enabled: parsed.data.enabled, validatedAt: new Date() }).onConflictDoUpdate({ target: [providerConnections.accountId, providerConnections.provider], set: { encryptedCredentials: encryptCredentials(parsed.data.credentials), enabled: parsed.data.enabled, validatedAt: new Date() } }); return Response.json({ data: { provider: parsed.data.provider, enabled: parsed.data.enabled } }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Connection failed" }, { status: 422 }); } }
export async function DELETE(request: Request) { const { userId } = await auth(); if (!userId) return Response.json({ error: "Unauthorized" }, { status: 401 }); const provider = new URL(request.url).searchParams.get("provider"); if (!provider || !providerTypes.includes(provider as typeof providerTypes[number])) return Response.json({ error: "Invalid provider" }, { status: 422 }); const account = await ensureAccount(userId); await getDb().delete(providerConnections).where(and(eq(providerConnections.accountId, account.id), eq(providerConnections.provider, provider as typeof providerTypes[number]))); return new Response(null, { status: 204 }); }
